name: deployment

on:
    push:
        branches: [main]

jobs: 
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Go
              uses:  actions/setup-go@v5
              with: 
                    go-version: "1.23.0"

            - name: Build App
              run: ./scripts/buildprod.sh

            - name: Authenticate with Google Cloud
              uses: google-github-actions/auth@v1
              with:
                credentials_json: ${{ secrets.GCP_CREDENTIALS }}
            
            - name: Set up Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v1
              with:
                project_id: ardent-rush-451423-q2